image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  
before_script:
  - chmod +x mvnw
  
maven-build:
  image: maven:3-jdk-8
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - target/*.jar
      
docker-build:
  stage: package
  script:
  - docker login registry.gitlab.com/gitlabcicd-group/devopsgitlabspringaws -u jasonlll881 -p $DEPLOY_TOKEN
  - docker build -t registry.gitlab.com/gitlabcicd-group/devopsgitlabspringaws/spring-docker:0.0.1 .
  - docker push registry.gitlab.com/gitlabcicd-group/devopsgitlabspringaws/spring-docker:0.0.1
  only:
  - master