image: java:8

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=./.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

cache:
  paths:
    - ./.m2/repository
  # keep cache across branch
  key: "$CI_BUILD_REF_NAME"


stages:
  - build
  - deploy
  
before_script:
  - chmod +x mvnw
  
build:
  stage: build
  script: ./mvnw package $MAVEN_CLI_OPTS
  artifacts:
    paths:
      - target/demo-0.0.1-SNAPSHOT.jar
      
      
dev:
  stage: deploy
  script:
  - echo "Command to deploy in AWS" 
  - ls -al
  - echo "ls previous folder"
  - ls -al target/
  only:
  - master