image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  
before_script:
  - chmod +x mvnw
  
maven-build:
#  image: maven:3-jdk-8
  stage: build
  script: 
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_TOKEN $CI_REGISTRY
  - docker build -t registry.gitlab.com/gitlabcicd-group/devopsgitlabspringaws/spring-docker:0.0.1 .
  - docker push registry.gitlab.com/gitlabcicd-group/devopsgitlabspringaws/spring-docker:0.0.1
  - ./mvnw package
  artifacts:
    paths:
      - target/*.jar
      
docker-build:
  stage: package
  script:
    - echo JLRM
  only:
  - master