image: java:8

stages:
  - build
  - deploy
  
before_script:
  - chmod +x mvnw
  
build:
  stage: build
  script: mvn package
  artifacts:
    paths:
      - target/demo-0.0.1-SNAPSHOT.jar
      
      
dev:
  stage: deploy
  script:
  - echo "Command to deploy in AWS"  
  only:
  - master