image: java:8

stages:
  - build
  - deploy
  
before_script:
  - chmod +x mvnw
  
build:
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - target/demo-0.0.1-SNAPSHOT.jar
      
      
dev:
  stage: deploy
  script:
  - https://gitlab.com/gitlabcicd-group/devopsgitlabspringaws/-/jobs/artifacts/master/raw/target/demo-0.0.1-SNAPSHOT.jar?job=build
  - echo "Command to deploy in AWS" 
  - ls
  only:
  - master